--[과제]
--1. 지난 자바 과제를 지원하는 테이블 생성
CREATE TABLE STUDENT(
    ID VARCHAR2(10)      CONSTRAINT STUDENT_ID_PK PRIMARY KEY,
    NAME VARCHAR2(10)    CONSTRAINT STUDENT_NAME_NN NOT NULL,
    GENDER VARCHAR2(5)   CONSTRAINT STUDENT_GENDER_NN NOT NULL,
    KOREA NUMBER(4)      CONSTRAINT STUDENT_KOREA_NN NOT NULL,
    ENGLISH NUMBER(4)    CONSTRAINT STUDENT_ENGLISH_NN NOT NULL,
    MATH NUMBER(4)       CONSTRAINT STUDENT_MATH_NN NOT NULL,
    SCIENCE NUMBER(4)    CONSTRAINT STUDENT_SCIENCE_NN NOT NULL
);

--2. 생성한 테이블에 5개 행 이상의 샘플 데이터 입력
INSERT INTO (SELECT ID, NAME, GENDER, KOREA, ENGLISH, MATH, SCIENCE FROM STUDENT)
VALUES ();

--3. 프로그램에 사용되는 데이터 처리를 위한 쿼리 작성 및 실행